### ISSUE TITLE
Trouble importing after successful pip install

### ISSUE THREAD

**Issue by spisupat** [microsoft/classy-fire#5]
Hi, thanks for this very interesting project, looking forward to using in lieu of guidance!

I was having trouble importing `classy_fire` after a successful pip install, even though my sys path has the correct install directory? Doesn’t import even with a local pip install (unless I am in the package’s directory)

**Comment by oribarilan** [comment]
@spisupat - issue is fixed in v0.1.7. Thanks for reporting!
